### PR TITLE
implement FLAP authentication for AIM v1.x-v3.0

### PR DESCRIPTION
**Pull request by mk6i**
@Ramen2X FYI, Retro AIM Server now supports AIM v3.x.

IIRC you opened an issue (that has since been lost) asking about this last year. Apologies if I'm misremembering!

### CODE REVIEW

**Comment by Ramen2X** [comment]
Awesome work! Thanks for remembering. I've continued to keep my eye on the project; I'm excited to give it another shot.

**Comment by mk6i** [comment]
Excellent, I'm cutting a new release today that will include this change. There are a couple caveats that I'll include in the release notes (such as chat rooms not currently working in 3.x).

**Comment by Ramen2X** [comment]
@mk6i I'm interested in putting together a video overview of Retro AIM Server for a YouTube channel to help bring it to the attention of a wider audience. If you're okay with it, I'd be interested in asking a few questions about the whole project. Is this something you'd be okay with or interested in? If so, what's the best way to directly contact you? (e-mail, IM service, etc.) Thanks!

**Comment by mk6i** [comment]
That sounds like fun! My email is mk6i@proton.me

**Comment by Ramen2X** [comment]
@mk6i Expect an email later today about the state of things (my mailbox isn't working right now regrettably)

**Pull request merged**
