### PR TITLE
DMR

### PR DESCRIPTION
**Pull request by RealBradCool**
Add this please

### CODE REVIEW

**Comment by mk6i** [comment]
What is this?

**Review by D3CL4NZ — COMMENTED** [review]
What exactly does this do?

**Comment by RealBradCool** [comment]
There is a dmr pichere i hacked to make icq work i found the fix by finding a qserf dmr in a thermal runway pichere and adding a few thongs into the photo and code to make it work

**Comment by RealBradCool** [comment]
so the dmr picture is the key to fixing dmr

**Pull request closed without merging**
